name: Branch for stable series
on:
  workflow_dispatch:
    inputs:
      ref:
        description: |
          Commit hash or other reference to use when branching. If not given
          defaults to 'main'.
        required: false
        default: 'main'

permissions:
  contents: write
  pull-requests: write

jobs:
  branch:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'canonical' }}
    environment: stable
    steps:
    - name: Checkout
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      with:
        ref: ${{ inputs.ref }}
        fetch-depth: 0
    - name: Create branch and bump version
      env:
        AUTHOR_NAME: "Anbox Bot"
        AUTHOR_EMAIL: "anbox-bot@canonical.com"
        ANBOX_CLOUD_CI_BOT_SSH_KEY: ${{ secrets.ANBOX_CLOUD_CI_BOT_SSH_KEY }}
        GH_TOKEN: ${{ github.token }}
      run: |
        # Setup SSH key based access so we can write a branch
        . "$GITHUB_WORKSPACE"/scripts/setup-gh-ssh.sh

        git config --global user.name "$AUTHOR_NAME"
        git config --global user.email "$AUTHOR_EMAIL"

        # First we create the new stable branch
        series="$(cat .base_version | cut -d. -f1,2)"
        minor="$(echo "$series" | cut -d. -f2)"
        next_minor=$((minor+1))
        next_version="1.$next_minor"
        branch_name=stable-"$series"
        git checkout -b "$branch_name"
        git push git@github-anbox-streaming-sdk:canonical/anbox-streaming-sdk "$branch_name"

        # Next we have to update main to include the new version number
        branch=bump-version-to-"$next_version"
        # If we already have a branch and PR we can stop here
        if git branch -a | grep -q "$branch" ; then
          exit 0
        fi
        git checkout -b "$branch"
        sed "s/${series}/${next_version}/g" -i .base_version js/anbox-stream-sdk.js
        git add .base_version js/anbox-stream-sdk.js
        git commit -m "chore: bump version to $next_version"
        git push git@github-anbox-streaming-sdk:canonical/anbox-streaming-sdk "$branch"
        gh pr create -B main -H "$branch" \
          --title "Bump version to $next_version" \
          --body "Automatically requested by workflow. Please close and reopen this PR to trigger workflows!"
