name: Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release'
        required: true
      target_commitish:
        description: |
          Target commitish (see GH API) for tag creation.
          Can be empty - it will default to the head of the branch it is run from.
        required: false

# To publish assets to on GitHub release pages
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: stable

    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0

    - name: Build
      run: |
        ./scripts/build.sh --create-tarball --version=${{ inputs.tag_name }}

    - name: Run tests
      run: |
        ./scripts/run-tests.sh

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "${{ inputs.tag_name }}" \
          anbox-streaming-sdk_${{ inputs.tag_name }}.zip \
          --target "${{ inputs.target_commitish || github.ref }}" \
          --title "${{ inputs.tag_name }}" \
          --notes "See https://documentation.ubuntu.com/anbox-cloud/reference/release-notes/${{ inputs.tag_name }}/ for more information."
