name: Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release'
        required: true
      target_commitish:
        description: |
          Target commitish (see GH API) for tag creation.
          Can be empty - it will default to the head of the branch it is run from.
        required: false

# To publish assets to on GitHub release pages
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: 0

    - name: Build
      run: |
        ./scripts/build.sh --create-tarball --version=${{ inputs.tag_name }}

    - name: Run tests
      run: |
        ./scripts/run-tests.sh

    - name: Release
      uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2
      with:
        files: anbox-streaming-sdk_${{ inputs.tag_name }}.zip
        tag_name: ${{ inputs.tag_name }}
        target_commitish: ${{ inputs.target_commitish }}
        body: |
          See https://documentation.ubuntu.com/anbox-cloud/reference/release-notes/${{ inputs.tag_name }}/ for more information.
